In [66]:
print("Hello World")

Hello World

In [36]:
# Loadi in a dataset
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [37]:
import pandas as pd
import numpy as np
import re
from sklearn.preprocessing import LabelEncoder

In [4]:
df.isnull().values.any

True

In [8]:
display(df)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [15]:
display(df)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

Remove missing values

In [19]:
df_missing = df[df.isnull().any(axis=1)]

In [28]:
display(df_missing)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

Correct  way:

In [46]:
missing_values = df.isnull().sum()
print("Missing values before cleaning:")
print(missing_values)

Missing values before cleaning:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# Handle missing values

In [49]:
df['Age'].fillna(df['age'].median(), inplace=True)
df.dropna(subset=['embarked'], inplace=True)

KeyError: 'Age'

Check for duplictes

In [29]:
df_missing.duplicated()

0      False
2      False
4      False
5      False
7      False
       ...
884     True
885    False
886     True
888    False
890    False
Length: 709, dtype: bool

clean them

In [30]:
df_clean = df_missing.drop_duplicates()

In [31]:
display(df_clean)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# 3. Inspect the "Sex" column for inconsistencies and standardize values.

In [33]:
df_clean['sex'].unique()

array(['male', 'female'], dtype=object)

In [32]:
df_clean['sex'].unique()

array(['male', 'female'], dtype=object)

# 4. Detect and handle outliers in the "Age" and "Fare" columns.

In [39]:
Q1_age = df_clean['age'].quantile(0.25)
Q3_age = df_clean['age'].quantile(0.75)
IQR_age = Q3_age - Q1_age

Q1_fare = df_clean['fare'].quantile(0.25)
Q3_fare = df_clean['fare'].quantile(0.75)
IQR_fare = Q3_fare - Q1_fare

In [40]:
display(IQR_fare)

18.1042

In [43]:
df_clean['family_size'] = df_clean['sibsp'] + df_clean['parch'] + 1

C:\Users\Admin\AppData\Local\Temp\ipykernel_3200\2254518114.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['family_size'] = df_clean['sibsp'] + df_clean['parch'] + 1

In [44]:
def family_group(size):
    if size == 1:
        return 'Alone'
    elif size <= 4:
        return 'Small'
    else:
        return 'Large'

df_clean['Family_Group'] = df_clean['Family_Size'].apply(family_group)

KeyError: 'Family_Size'

A function to reove NA's and duplicates

In [61]:
def clean_dataframe(df):
    """
    Remove rows with missing values and duplicate rows from a DataFrame.
    Returns a cleaned copy of the DataFrame.
    """
    df_clean = df.dropna()            # remove rows with any NA
    df_clean = df_clean.drop_duplicates()  # remove duplicate rows
    df_clean = df_clean.reset_index(drop=True)  # tidy index
    return df_clean

In [62]:
display(df_clean)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,1
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True,1
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,1
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,6
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,4
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

create a function that goes though every numerical col, removes utliers and outputs a clean DF and an outlier DF

In [67]:
# Loadi in a dataset
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [71]:
import pandas as pd

def remove_outliers(df):
    """
    Detects and removes outliers from all numerical columns using the IQR method.
    Returns:
        df_clean  - DataFrame without outliers
        df_outliers - DataFrame containing only outlier rows
    """
    df_numeric = df.select_dtypes(include='number')
    df_outliers = pd.DataFrame()

    # Start with all rows marked as non-outliers
    mask = pd.Series([True] * len(df), index=df.index)

    for col in df_numeric.columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        # Identify outliers for this column
        col_outliers = (df[col] < lower) | (df[col] > upper)

        # Update global mask
        mask = mask & (~col_outliers)

    # Clean DF = rows that are never outliers
    df_clean = df[mask].reset_index(drop=True)

    # Outlier DF = rows removed
    df_outliers = df[~mask].reset_index(drop=True)

    return df_clean, df_outliers

In [72]:
display (df_clean)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,1
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True,1
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,1
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,6
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,4
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [ ]:
r

In [75]:
df_clean, df_outliers = remove_outliers(df)

In [77]:
print(df_outliers)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           1       1  female  38.0      1      0  71.2833        C   First
1           0       3    male   2.0      3      1  21.0750        S   Third
2           1       3  female  27.0      0      2  11.1333        S   Third
3           1       3  female   4.0      1      1  16.7000        S   Third
4           0       3    male  39.0      1      5  31.2750        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
288         1       1  female  47.0      1      1  52.5542        S   First
289         1       1  female  56.0      0      1  83.1583        C   First
290         1       2  female  25.0      0      1  26.0000        S  Second
291         0       3  female  39.0      0      5  29.1250        Q   Third
292         0       3  female   NaN      1      2  23.4500        S   Third

       who  adult_male deck  embark_town alive  alone
0    woman       False    C    Cherbourg   yes  False
1    child       False  NaN  Southampton    no  False
2    woman       False  NaN  Southampton   yes  False
3    child       False    G  Southampton   yes  False
4      man        True  NaN  Southampton    no  False
..     ...         ...  ...          ...   ...    ...
288  woman       False    D  Southampton   yes  False
289  woman       False    C    Cherbourg   yes  False
290  woman       False  NaN  Southampton   yes  False
291  woman       False  NaN   Queenstown    no  False
292  woman       False  NaN  Southampton    no  False

[293 rows x 15 columns]